
const MONGODB_URL = "mongodb://localhost:27017/";

const CRYPTO_ITERATIONS = 4000;

const CRYPTO_KEY_LEN = 4096

const CRYPTO_ALG = 'sha256';

const HAND_SIZE = 10;

const BLANK_SPACE = '______';

const GAME_CAPACITY = 100;

const NEXT_ROUND_DELAY = 10000; //10 seconds

const SERVER_PORT = 8989;

const SESSION_SECRET = "4wehjgwegfwkw3k23";

const SESSION_COOKIE_KEY = "cah.sid";

const MAX_MESSAGES = 200;

const MAX_MESSAGE_LENGTH = 300;

module.exports = {
	MONGODB_URL:MONGODB_URL,
	CRYPTO_ITERATIONS:CRYPTO_ITERATIONS,
	CRYPTO_KEY_LEN:CRYPTO_KEY_LEN,
	CRYPTO_ALG:CRYPTO_ALG,
	HAND_SIZE:HAND_SIZE,
	BLANK_SPACE:BLANK_SPACE,
	GAME_CAPACITY:GAME_CAPACITY,
	SERVER_PORT:SERVER_PORT,
	SESSION_SECRET:SESSION_SECRET,
	SESSION_COOKIE_KEY:SESSION_COOKIE_KEY
};